version: '3.1'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - 5400:5432
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: postgres
      POSTGRES_DB: chatapp
    volumes:
      - my_postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
volumes:
  my_postgres_data:
